name: chainpulse
version: 1.0.0
config-version: 2
profile: chainpulse

model-paths: ["models"]
vars:
  raw_schema: public
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  chainpulse:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts
    analytics:
      +materialized: incremental
      +schema: analytics
      +on_schema_change: "sync_all_columns"

seeds:
  chainpulse:
    +schema: marts
    known_tokens:
      +column_types:
        token_address: varchar(42)
        symbol: varchar(20)
        name: varchar(100)
        decimals: integer
        coingecko_id: varchar(50)
