chainpulse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('PGHOST', 'localhost') }}"
      port: "{{ env_var('PGPORT', '5432') | int }}"
      user: "{{ env_var('PGUSER', 'postgres') }}"
      password: "{{ env_var('PGPASSWORD', '') }}"
      dbname: "{{ env_var('PGDATABASE', 'chainpulse') }}"
      schema: public
      sslmode: "{{ env_var('PGSSLMODE', 'prefer') }}"
      connect_timeout: 10
    prod:
      type: postgres
      host: "{{ env_var('PGHOST') }}"
      port: "{{ env_var('PGPORT', '5432') | int }}"
      user: "{{ env_var('PGUSER') }}"
      password: "{{ env_var('PGPASSWORD') }}"
      dbname: "{{ env_var('PGDATABASE') }}"
      schema: public
      sslmode: "{{ env_var('PGSSLMODE', 'require') }}"
      connect_timeout: 10
